version: "3.8"

services:
  go:
    image: golang:latest
    container_name: scootin_aboot__go
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./migration:/app/migration
      - ./.env:/app/.env
      - ./.env.dist:/app/.env.dist
      - ./.gitignore:/app/.gitignore
      - ./README.md:/app/README.md
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]
  db:
    image: mysql:latest
    container_name: scootin_aboot__db
    ports:
      - "${EXPOSE_DB_PORT}:3306"
    volumes:
      - ./migration:/migration
      - ./scootin_aboot.sql:/scootin_aboot.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: scootin_aboot
