// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/scooter_occupation_repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockScooterOccupationRepository is a mock of ScooterOccupationRepository interface.
type MockScooterOccupationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScooterOccupationRepositoryMockRecorder
}

// MockScooterOccupationRepositoryMockRecorder is the mock recorder for MockScooterOccupationRepository.
type MockScooterOccupationRepositoryMockRecorder struct {
	mock *MockScooterOccupationRepository
}

// NewMockScooterOccupationRepository creates a new mock instance.
func NewMockScooterOccupationRepository(ctrl *gomock.Controller) *MockScooterOccupationRepository {
	mock := &MockScooterOccupationRepository{ctrl: ctrl}
	mock.recorder = &MockScooterOccupationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScooterOccupationRepository) EXPECT() *MockScooterOccupationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScooterOccupationRepository) Create(scooterUuid, userUuid uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", scooterUuid, userUuid)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScooterOccupationRepositoryMockRecorder) Create(scooterUuid, userUuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScooterOccupationRepository)(nil).Create), scooterUuid, userUuid)
}

// DeleteByScooterUuidAndUserUuid mocks base method.
func (m *MockScooterOccupationRepository) DeleteByScooterUuidAndUserUuid(scooterUuid, userUuid uuid.UUID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByScooterUuidAndUserUuid", scooterUuid, userUuid)
	ret0, _ := ret[0].(bool)
	return ret0
}

// DeleteByScooterUuidAndUserUuid indicates an expected call of DeleteByScooterUuidAndUserUuid.
func (mr *MockScooterOccupationRepositoryMockRecorder) DeleteByScooterUuidAndUserUuid(scooterUuid, userUuid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByScooterUuidAndUserUuid", reflect.TypeOf((*MockScooterOccupationRepository)(nil).DeleteByScooterUuidAndUserUuid), scooterUuid, userUuid)
}
